ngettext stub missing. Some demuxer plugins do not load due to an undefined reference to "ngettext", when xine-lib is compiled with --disable-nls.
CVS patchset: 2604
CVS date: 2002/09/04 15:25:26